--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/MiningDimension
build-by-default: true
projects:
  MiningDimension:
    path: ""
    icon: "icon.png"
    excludeDirs:
      - tests
      - .github
      - build
      - phpstan
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
...
