name: MiningDimension
main: jasonw4331\MiningDimension\MiningDimension
src-namespace-prefix: jasonw4331\MiningDimension
version: 1.0.0
api: 5.0.0
author: jasonw4331
description: "A plugin which creates a world designed for mining"
depend:
  - Customies
softdepend:
  - NativeDimensions