#  __  __   _           _                   _____    _                                    _
# |  \/  | (_)         (_)                 |  __ \  (_)                                  (_)
# | \  / |  _   _ __    _   _ __     __ _  | |  | |  _   _ __ ___     ___   _ __    ___   _    ___    _ __
# | |\/| | | | | '_ \  | | | '_ \   / _` | | |  | | | | | '_ ` _ \   / _ \ | '_ \  / __| | |  / _ \  | '_ \
# | |  | | | | | | | | | | | | | | | (_| | | |__| | | | | | | | | | |  __/ | | | | \__ \ | | | (_) | | | | |
# |_|  |_| |_| |_| |_| |_| |_| |_|  \__, | |_____/  |_| |_| |_| |_|  \___| |_| |_| |___/ |_|  \___/  |_| |_|
#                                    __/ |
#                                   |___/
#------------------------------------------------------------------------------------------------------------
# Do you want to enable Sticky ore in the mining dimension?
# Value can be true or false
Sticky Ore: true
# how tall should the mining world be?
# Value can be from 16 to 256
Surface Height: 80
# What block type should be on the world surface?
# Value can be Grass or Stone
Surface Block: Grass
# Should the mining dimension always be daytime?
# Value can be true or false
Always Day: true
# Should mob spawning be allowed in the mining dimension?
# Value can be true or false
Allow Mob Spawning: true